version: '2'
services:
  engine:
    container_name: engine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bridge_adaptivity
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
