# docker-compose file for local development

version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

volumes:
  pgdata:
